import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ProvidersWrapper } from '@/src/features/ProvidersWrapper/ProvidersWrapper';
import { Layout } from '@/src/layout';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProvidersWrapper>
          <Layout>{children}</Layout>
        </ProvidersWrapper>
      </body>
    </html>
  );
}
