import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "material-symbols";
import "./globals.css";
import "./globalicons.css";
import { ProvidersWrapper } from "@/src/features/ProvidersWrapper/ProvidersWrapper";
import { Layout } from "@/src/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={[inter.className].join(" ")}>
        <ProvidersWrapper>
          {/* <Layout>{children}</Layout> */}
          <>{children}</>
        </ProvidersWrapper>
      </body>
    </html>
  );
}
